### ISSUE TITLE
Pulsanti condivisione

### ISSUE THREAD

**Issue by massimozotti** [openpuglia-cloud/openpuglia-web-site#10]
I pulsanti di condivisione che ci sono in basso a destra sono solo quelli dei social network più sfigati?? Dove sono Facebook e Twitter?? :)

(i pulsanti sono fatti per condividere la singola pagina e non l'intero sito, vero?)

**Comment by marfago** [comment]
Please send me an email lisitng all the needed socials (and accounts).

**Comment by massimozotti** [comment]
Do you need me to write in english?
Needed social networks are Facebook & Twitter - and the others already present, they are OK.
No accounts needed, the users sharing contents decides which account he wants to use.

**Comment by marfago** [comment]
Done
