### ISSUE TITLE
(low priority) Frame invisible in web page 

### ISSUE THREAD

**Issue by massimozotti** [openpuglia-cloud/openpuglia-web-site#13]
Could you please check why the frame at the top of this blog post is not visible?
https://euve102295.serverprofi24.net/openpuglia/node/16

(very low priority)
the same frame is visible here: http://opendatabari.github.io/blog/opendata/openstreetmap/2014/05/06/tutti-i-luoghi-del-mito-geografia-di-san-nicola.html

**Comment by marfago** [comment]
Fixed
