### ISSUE TITLE
Caricamento Immagini

### ISSUE THREAD

**Issue by massimozotti** [openpuglia-cloud/openpuglia-web-site#2]
Non riesco ad inserire immagini nei post.
Nella pagina di creazione di un evento c'era apparentemente la possibilità di caricare una foto, ma cliccando sul link si è aperto un pop-up che diceva "non sei autorizzato"

**Comment by marfago** [comment]
Can you please try again?

**Comment by massimozotti** [comment]
![image](https://cloud.githubusercontent.com/assets/6594325/11767448/3bf2e528-a1ae-11e5-8a9f-fd2651f0c96c.png)

Anche dopo aver caricato l'immagine, non viene visualizzata nel post.
Inoltre sembra che perda le proprietà impostate per l'immagine (es. width & lenght) dopo il salvataggio

**Comment by marfago** [comment]
Does it work now?

**Comment by massimozotti** [comment]
Anche la formattazione del Titolo2 non va:
![image](https://cloud.githubusercontent.com/assets/6594325/11767463/9f23e85e-a1ae-11e5-87ab-14e30389ce5e.png)

**Comment by massimozotti** [comment]
direi di no

2015-12-13 15:30 GMT+01:00 marfago notifications@github.com:

**Comment by massimozotti** [comment]
![image](https://cloud.githubusercontent.com/assets/6594325/11767509/67c92368-a1b0-11e5-87f5-a72354e020c2.png)

**Comment by marfago** [comment]
Shoud be fixed now.
