### ISSUE TITLE
Modificare l'autore di un post 

### ISSUE THREAD

**Issue by massimozotti** [openpuglia-cloud/openpuglia-web-site#3]
E' possibile modificare l'autore di un post dopo che è stato pubblicato?
Inoltre non è carino che esca "massimozotti's blog" perché sembra una cosa strana; meglio che esca semplicemente il nick dell'autore, senza <'s blog>

**Comment by marfago** [comment]
Yes, it is. Just edit the post and select "authoring information" on the left-hand side.

**Comment by massimozotti** [comment]
Need to be an admin to do that?

**Comment by marfago** [comment]
Done
