### ISSUE TITLE
Mission non editabile

### ISSUE THREAD

**Issue by massimozotti** [openpuglia-cloud/openpuglia-web-site#4]
La pagina che dovrebbe descrivere la mission non è editabile

**Comment by marfago** [comment]
Could you please retry?

**Comment by massimozotti** [comment]
Sono riuscito ad editare. 
Mi sembra ci sia un problema nella pagina che non rende la formattazione dei titoli dei paragrafi:
https://euve102295.serverprofi24.net/openpuglia/node/1

**Comment by massimozotti** [comment]
Confermo qualche problema nella visualizzazione su web dei contenuti inseriti nell'editor : ho inserito nel blog post il tag per il widget di eventbrite e non se l'è cacato: 
div style="width:100%; text-align:left;" ><iframe  src="//eventbrite.it/tickets-external?eid=19682972300&ref=etckt" frameborder="0" height="260" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" ><a class="powered-by-eb" style="color: #dddddd; text-decoration: none;" target="_blank" href="http://www.eventbrite.it/r/etckt">Con tecnologia Eventbrite</a></div></div
