### ISSUE TITLE
Sezioni da inserire

### ISSUE THREAD

**Issue by massimozotti** [openpuglia-cloud/openpuglia-web-site#5]
Bisogna inserire le sezioni:
- Lavori
- Staff
- Contatti

**Comment by massimozotti** [comment]
Sarebbe carino che la sezione "Staff" fosse simile a questa: http://www.spaghettiopendata.org/community

**Comment by marfago** [comment]
You can do it by yourself, just go 
here https://euve102295.serverprofi24.net/openpuglia/#overlay=admin/structure/menu and edit navigation menu.
