### ISSUE TITLE
integrazione mailing list

### ISSUE THREAD

**Issue by massimozotti** [openpuglia-cloud/openpuglia-web-site#6]
Vorrei che in home page apparisse integrata in basso la mailing list di openpuglia, come accade sull'home page di spaghettiopendata.org

**Comment by marfago** [comment]
Could you please attach here a picture of it?

**Comment by massimozotti** [comment]
![immagine](https://cloud.githubusercontent.com/assets/6594325/11793070/d77e5116-a2a9-11e5-83e6-e4de6543d663.png)

**Comment by massimozotti** [comment]
![immagine](https://cloud.githubusercontent.com/assets/6594325/11793082/eebbc1ce-a2a9-11e5-97f2-4ada77b0099c.png)

**Comment by marfago** [comment]
Done
